name: CI

on:
    pull_request:
        branches: [prd, stg, dev]
        types: [opened, reopened, synchronize, edited]
        paths-ignore: # Pushes that include only these changed files won't trigger actions
        - '**/README.md'
        - '**/.gitignore'
        - '**/doc/*'
env:    
    tf_version: ">=1.4.5" # must match value in terraform/modules/app/main.tf

jobs:
    format:
      name: Terraform Format
      runs-on: ubuntu-latest
      steps:
        - name: Check Terraform Formatting
          run: terraform fmt -check -recursive

    checkMeds:
      name: Check Meds (merge every day)
      runs-on: ubuntu-latest
      steps:
          - name: Check Meds
            uses: byuawsfhtl/MedsAction@v1.0.0